[package]
name = "discus"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "discus"

[[bin]]
name = "opdecode"
path = "src/opdecode.rs"

[[bin]]
name = "miller_rabin"
path = "src/miller_rabin.rs"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
